name: Java CI

on: push
branches-ignore: 
actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts
        path: 'target/petclinic.war'
        
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
        # Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: # optional
        app-name: thepetclinic
        package: 'target/petclinic.war'
        slot-name: production
