name: Build & Deploy Pet Clinic

on: push

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Unit Tests
      run: mvn test
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: SonarCloud scan
      run: mvn verify sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.sonarToken }}
        
    - name: Azure WebApp Deployment
      uses: Azure/webapps-deploy@v1
      with:
        publish-profile: ${{ secrets.stagingPublishProfile }}
        app-name: thepetclinic
        package: '${{ github.workspace }}/target/*.war'
        slot-name: thepetclinic-staging
        
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
    
    - run: |
        az storage blob upload -c petclinic -f '${{ github.workspace }}/target/petclinic.war' -n 'petclinic_$GITHUB_RUN_NUMBER' \
        --account-name warfiles \
        --account-key ${{ secrets.azureStorage }}
