name: Pet Clinic CI

on: push

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
        
    - name: Azure WebApp Deployment
      uses: Azure/webapps-deploy@v1
      with:
        app-name: thepetclinic
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        slot-name: thepetclinic-staging 
